export const GET_VG = 'GET_VG'
export const SEARCH_BY_NAME = 'SEARCH_BY_NAME'
export const ORDER_AND_FILTER_VIDEOGAMES = 'ORDER_AND_FILTER_VIDEOGAMES'
export const SET_PAGE = 'SET_PAGE'
export const SET_ORDER = 'SET_ORDER'
export const SET_ORIGIN = 'SET_ORIGIN'
export const SET_GENRE = 'SET_GENRE'
export const SET_LOADING = 'SET_LOADING'
export const SET_FIRST_RENDER = 'SET_FIRST_RENDER'

